server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 3
        order_inserts: true
        order_updates: true
        generate_statistics: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 213660715303-8kdmis4acl8l0omrqtebrd2v3ivd5hb7.apps.googleusercontent.com
            client-secret: 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
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
        completions-path: chat/completions
        options:
          model: gemini-2.5-flash

debug: true

mistral:
  api:
    base-url: https://api.mistral.ai
    key: ${MISTRAL_API_KEY}

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 36000
  refreshable-duration: 360000

vnpay:
  tmn-code: "${VNPAY_TMN_CODE}"
  secret-key: "${VNPAY_SECRET_KEY}"
  return-url: "${VNPAY_RETURN_URL}"

ghn:
  base-url: https://dev-online-gateway.ghn.vn/shiip/public-api
  token: ${GHN_TOKEN}
  shop-id: ${GHN_SHOP_ID}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}