server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 213660715303-8kdmis4acl8l0omrqtebrd2v3ivd5hb7.apps.googleusercontent.com
            client-secret: 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

jwt:
  signerKey: "8591f80b80ac9777c53927e02c6cd5e98f4ed5782999c1ea40cbc2bb684806f1"
  valid-duration: 3600
  refreshable-duration: 36000

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}