package com.e_commerce.e_commerce.enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@FieldDefaults(level = AccessLevel.PRIVATE)
@NoArgsConstructor
@AllArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
    KEY_INVALID(8888, "Uncategorized error", HttpStatus.BAD_REQUEST),
    USERNAME_INVALID(1001, "Username at least {min} characters", HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(1002, "Password at least {min} characters", HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(1003, "This user does not already exist", HttpStatus.NOT_FOUND),
    USERNAME_REQUIRED(1004, "Username is required", HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(1005, "Password is required", HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(1006, "Email is required", HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1007, "Email is invalid", HttpStatus.BAD_REQUEST),
    USER_ALREADY_EXISTS(1008, "This user already exists", HttpStatus.CONFLICT),
    UNAUTHENTICATED(1009, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    SECURITY(1010, "Security", HttpStatus.UNAUTHORIZED),
    TOKEN_REQUIRED(1011, "Token is required", HttpStatus.BAD_REQUEST),
    ROLE_NAME_REQUIRED(1012, "Role name is required", HttpStatus.BAD_REQUEST),
    PERMISSION_NAME_REQUIRED(1013, "Permission name is required", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(1014, "Unauthorized", HttpStatus.FORBIDDEN),
    PRODUCT_NOT_EXISTED(1015, "This product does not already exist", HttpStatus.NOT_FOUND),
    PRODUCT_NAME_REQUIRED(1016, "Product name is required", HttpStatus.BAD_REQUEST),
    PRODUCT_CATEGORY_REQUIRED(1017, "Product category is required", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_PRICE_REQUIRED(1018, "Product variant price is required", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_PRICE_INVALID(1019, "Product variant price must be at least 0", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_INSUFFICIENT_STOCK(1020, "Product variant stock is insufficient", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_ID_REQUIRED(1021, "Product variant ID is required", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_QUANTITY_INVALID(1022, "Product variant quantity must be at least 0", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_QUANTITY_REQUIRED(1023, "Product variant quantity is required", HttpStatus.BAD_REQUEST),
    PRODUCT_NAME_INVALID(1024, "Product name at least {min} characters", HttpStatus.BAD_REQUEST),
    PRODUCT_CATEGORY_INVALID(1025, "Product category at least {min} characters", HttpStatus.BAD_REQUEST),
    CART_ID_REQUIRED(1026, "Cart ID is required", HttpStatus.BAD_REQUEST),
    PRICE_AT_PURCHASE_REQUIRED(1027, "Price at purchase is required", HttpStatus.BAD_REQUEST),
    PRICE_AT_PURCHASE_INVALID(1028, "Price at purchase must be at least 1", HttpStatus.BAD_REQUEST),
    CART_NOT_EXISTED(1029, "This cart does not already exist", HttpStatus.NOT_FOUND),
    CART_ITEM_NOT_EXISTED(1030, "This cart item does not already exist", HttpStatus.NOT_FOUND),
    INVALID_GENDER(1031, "Gender is invalid", HttpStatus.BAD_REQUEST),
    INVALID_CATEGORY(1032, "Category is invalid", HttpStatus.BAD_REQUEST),
    SKU_REQUIRED(1033, "Sku is required", HttpStatus.BAD_REQUEST),
    SKU_ALREADY_EXISTED(1034, "Sku does already exist", HttpStatus.NOT_FOUND),
    PRODUCT_VARIANT_NOT_EXISTED(1035, "Product variant does not already exist", HttpStatus.NOT_FOUND),
    PRODUCT_IS_NOT_ACTIVE(1036, "Product is not active", HttpStatus.BAD_REQUEST),
    VOUCHER_CODE_NOT_EXISTED(1037, "Voucher code does not already exist", HttpStatus.NOT_FOUND),
    INVALID_PAYMENT_METHOD(1038, "Payment method is invalid", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_WEIGHT_INVALID(1039, "Product variant weight must be at least 0kg", HttpStatus.BAD_REQUEST),
    VOUCHER_EXPIRED(1040, "Voucher is expired", HttpStatus.BAD_REQUEST),
    VOUCHER_OUT_OF(1041, "Voucher is no longer valid", HttpStatus.BAD_REQUEST),
    RECEIVER_NAME_REQUIRED(1042, "Receiver name is required", HttpStatus.BAD_REQUEST),
    RECEIVER_PHONE_REQUIRED(1043, "Receiver phone is required", HttpStatus.BAD_REQUEST),
    SHIPPING_ADDRESS_REQUIRED(1044, "Shipping address is required", HttpStatus.BAD_REQUEST),
    PAYMENT_METHOD_REQUIRED(1045, "Payment method is required", HttpStatus.BAD_REQUEST),
    ORDER_NOT_EXISTED(1046, "Order does not already exist", HttpStatus.NOT_FOUND),
    TOKEN_NOT_FOUND(1047, "Verification token not found", HttpStatus.BAD_REQUEST),
    TOKEN_EXPIRED(1048, "Verification token has expired", HttpStatus.BAD_REQUEST),
    INVALID_CHECKOUT_STATUS(1049, "Checkout status is invalid", HttpStatus.BAD_REQUEST),
    INVALID_DATE_RANGE(1050, "Start date must be before or equal to end date", HttpStatus.BAD_REQUEST),
    VOUCHER_CODE_REQUIRED(1051, "Voucher code is required", HttpStatus.BAD_REQUEST),
    VOUCHER_VALID_FROM_REQUIRED(1052, "Voucher valid from is required", HttpStatus.BAD_REQUEST),
    VOUCHER_VALID_TO_REQUIRED(1053, "Voucher valid to is required", HttpStatus.BAD_REQUEST),
    VOUCHER_USAGE_LIMIT_REQUIRED(1054, "Voucher usage limit is required", HttpStatus.BAD_REQUEST),
    VOUCHER_CATEGORY_REQUIRED(1055, "Voucher category is required", HttpStatus.BAD_REQUEST),
    VOUCHER_DISCOUNT_AMOUNT_INVALID(1056, "Voucher discount amount must be at least 1", HttpStatus.BAD_REQUEST),
    VOUCHER_DISCOUNT_PERCENT_INVALID(1057, "Voucher discount percent must be between 1 and 100", HttpStatus.BAD_REQUEST),
    VOUCHER_USAGE_LIMIT_INVALID(1058, "Voucher usage limit must be at least 1", HttpStatus.BAD_REQUEST),
    VOUCHER_USAGE_COUNT_INVALID(1059, "Voucher usage count must be at least 0", HttpStatus.BAD_REQUEST),
    VOUCHER_VALID_FROM_INVALID(1060, "Voucher valid from must be in the present or future", HttpStatus.BAD_REQUEST),
    VOUCHER_VALID_TO_INVALID(1061, "Voucher valid to must be in the future", HttpStatus.BAD_REQUEST),
    VOUCHER_DISCOUNT_BOTH_PRESENT(1062, "Only one of discount amount or discount percent should be provided", HttpStatus.BAD_REQUEST),
    VNPAY_AMOUNT_NOT_MATCH(1063, "VNPAY amount does not match order amount", HttpStatus.BAD_REQUEST),
    VNPAY_STATUS_NOT_MATCH(1064, "VNPAY status does not match order status", HttpStatus.BAD_REQUEST),
    WRONG_PASSWORD(1065, "The old password is incorrect", HttpStatus.BAD_REQUEST),
    OLD_PASSWORD_REQUIRED(1066, "Old password is required", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_REQUIRED(1067, "New password is required", HttpStatus.BAD_REQUEST),
    OTP_INVALID(1068, "OTP is invalid", HttpStatus.BAD_REQUEST),
    OTP_REQUIRED(1069, "OTP is required", HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_IN_USE(1070, "Email is already in use", HttpStatus.CONFLICT),
    EMAIL_SAME_AS_OLD(1071, "New email must be different from old email", HttpStatus.BAD_REQUEST),
    GHN_HTTP_ERROR(2001, "Failed to communicate with GHN API (HTTP Error)", HttpStatus.BAD_GATEWAY),
    GHN_EMPTY_RESPONSE_BODY(2002, "GHN API returned an empty response body", HttpStatus.BAD_GATEWAY),
    GHN_DATA_NULL(2003, "GHN API response 'data' field is null", HttpStatus.BAD_GATEWAY),
    VOUCHER_NOT_ACTIVE(2004, "Voucher not active", HttpStatus.BAD_REQUEST),
    CART_ITEM_NOT_IN_CART(2005, "Cart item does not belong to the current cart", HttpStatus.BAD_REQUEST),
    MIN_ORDER_VALUE_REQUIRED(2006, "Minimum order value is required", HttpStatus.BAD_REQUEST),
    MIN_ORDER_VALUE_INVALID(2007, "Minimum order value must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
    MAX_DISCOUNT_AMOUNT_INVALID(2008, "Maximum discount amount must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_LENGTH_INVALID(2009, "Product variant length at least 0", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_WIDTH_INVALID(2010, "Product variant width at least 0", HttpStatus.BAD_REQUEST),
    PRODUCT_VARIANT_HEIGHT_INVALID(2011, "Product variant height at least 0", HttpStatus.BAD_REQUEST),
    PRODUCT_REVIEW_NOT_EXISTED(3001, "Product review does not already exist", HttpStatus.BAD_REQUEST),
    PRODUCT_ID_REQUIRED(3002, "Product ID cannot be blank", HttpStatus.BAD_REQUEST),
    RATING_REQUIRED(3003, "Rating is required", HttpStatus.BAD_REQUEST),
    RATING_MIN_INVALID(3004, "Rating must be at least 1", HttpStatus.BAD_REQUEST),
    RATING_MAX_INVALID(3005, "Rating cannot exceed 5", HttpStatus.BAD_REQUEST),
    ;

    int code;
    String message;
    HttpStatusCode statusCode;
}
